export const MAX_EXACT_MATCH_LENGTH = 300
export const MIN_LENGTH_WITHOUT_CONTEXT = 20
export const ITERATIONS_BEFORE_ADDING_CONTEXT = 1
export const WORDS_TO_ADD_FIRST_ITERATION = 3
export const WORDS_TO_ADD_SUBSEQUENT_ITERATIONS = 1
export const TRUNCATE_RANGE_CHECK_CHARS = 10000
export const MAX_DEPTH = 500
